spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb+srv://ntsa_azure:Dbj5h4EVBbDhQxY@dil0001.dx94z.mongodb.net/ntsa_azure?retryWrites=true&w=majority
      database: ntsa_azure

mybatis:
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations:
    - classpath:/mapper/*.xml

server:
  port: 8000

jt-server:
  jt808:
    enable: true
    port:
      udp: 7611
      tcp: 7611
    media-file:
      path: /home/jt808/media_file
    alarm-file:
      host: 20.87.8.186
      port: 7612
  alarm-file:
    enable: true
    port: 7612
    path: /home/jt808/alarm_file

blob:
  connection-string: DefaultEndpointsProtocol=https;AccountName=jt808;AccountKey=8uExqj/qRo58emVrpn9zkACocoMaFqycQheBzLb9rjfp2JQZRXMacaAwWjo/f7oQ+dzP6OusC32lXfJmF+amtA==;EndpointSuffix=core.windows.net
  container-name: alerts

